---
name: EconomyEnchant
version: 1.0.4
main: MulqiGaming64\EconomyEnchant\EconomyEnchant
api: 5.0.0
author: XanderID
description: a EconomyEnchant Shop in UI
softdepend:
 - BedrockEconomy
 - VanillaEC

permissions:
 economyenchant.cmd:
  default: true
  description: EconomyEnchant Commands
...
